server:
  port: 8090
  servlet:
    context-path: /

spring:
  application:
    name: office
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/office?useSSL=false
    username: office
    password: office
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8

mybatis:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.sitech.aicp: debug
